baseURL = 'https://pygrum.github.io/'
languageCode = 'en-us'
title = 'Pygrum'
theme = 'archie'
copyright = "© Pygrum"
author = 'Pygrum'
publishdir = 'docs'
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "pygrum-security"

paginate = 5

[params.theme]
palette = 'base16-dark'

[params]
mode = 'dark'
title = 'Pygrum'
useCDN = false
subtitle = 'Malware R&D, Reverse Engineering and Offensive Security'
customcss = ["css/extended.css"]

[[params.social]]
name = 'GitHub'
icon = 'github'
url = 'https://github.com/pygrum'

[[params.social]]
name = 'Twitter'
icon = 'twitter'
url = 'https://twitter.com/pygrumsec'

[menu]

	[[menu.main]]
	name = "Posts"
	url = "/posts/"
	weight = 3

	[[menu.main]]
	name = "About"
	url = "/about/"
	weight = 1
	
	[[menu.main]]
	name = "Tags"
	url = "/tags"
	weight = 1
